AWSTemplateFormatVersion: '2010-09-09'
Description: 'CodeBuild project for EFS setup (one-time execution)'

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - staging
      - production
  
  EFSFileSystemId:
    Type: String
    Description: EFS File System ID
    Default: fs-03774cd22d8f9b3d9
  
  VPCId:
    Type: String
    Description: VPC ID where EFS is located
  
  PrivateSubnetIds:
    Type: CommaDelimitedList
    Description: Private subnet IDs (comma-separated)
  
  SecurityGroupId:
    Type: String
    Description: Security group that can access EFS

Resources:
  # CodeBuild Service Role
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${Environment}-codebuild-efs-setup-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonElasticFileSystemClientFullAccess
      Policies:
        - PolicyName: CodeBuildBasePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*'
              - Effect: Allow
                Action:
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                  - ec2:DescribeSubnets
                  - ec2:DescribeSecurityGroups
                  - ec2:DescribeDhcpOptions
                  - ec2:DescribeVpcs
                  - ec2:CreateNetworkInterfacePermission
                Resource: '*'
              - Effect: Allow
                Action:
                  - elasticfilesystem:ClientMount
                  - elasticfilesystem:ClientWrite
                  - elasticfilesystem:ClientRootAccess
                  - elasticfilesystem:DescribeMountTargets
                Resource: !Sub 'arn:aws:elasticfilesystem:${AWS::Region}:${AWS::AccountId}:file-system/${EFSFileSystemId}'

  # CodeBuild Project
  EFSSetupProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub '${Environment}-efs-setup'
      Description: One-time setup for EFS (model download + library install)
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: aws/codebuild/standard:7.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: EFS_MOUNT_POINT
            Value: /mnt/efs
          - Name: MODEL_NAME
            Value: all-MiniLM-L6-v2
      Source:
        Type: NO_SOURCE
        BuildSpec: |
          version: 0.2
          env:
            variables:
              EFS_MOUNT_POINT: /mnt/efs
              MODEL_NAME: all-MiniLM-L6-v2
          phases:
            install:
              runtime-versions:
                python: 3.11
              commands:
                - echo "Installing dependencies..."
                - pip3 install --upgrade pip
                - echo "Installing torch first (largest dependency)..."
                - pip3 install --no-cache-dir torch --index-url https://download.pytorch.org/whl/cpu
                - echo "Installing sentence-transformers..."
                - pip3 install --no-cache-dir sentence-transformers
                - echo "Installing lancedb..."
                - pip3 install --no-cache-dir lancedb
                - echo "Installing boto3..."
                - pip3 install --no-cache-dir boto3
            pre_build:
              commands:
                - echo "Verifying EFS mount..."
                - df -h
                - ls -la $EFS_MOUNT_POINT
                - echo "EFS mounted successfully"
            build:
              commands:
                - echo "Step 1 - Downloading ML model to EFS..."
                - mkdir -p $EFS_MOUNT_POINT/models
                - |
                  python3 << 'EOF'
                  from sentence_transformers import SentenceTransformer
                  import os
                  model_name = os.environ['MODEL_NAME']
                  efs_mount = os.environ['EFS_MOUNT_POINT']
                  model_path = os.path.join(efs_mount, 'models', model_name)
                  print(f"Downloading {model_name}...")
                  model = SentenceTransformer(model_name)
                  model.save(model_path)
                  print(f"Model saved to {model_path}")
                  EOF
                - echo "Step 2 - Installing Python libraries to EFS..."
                - mkdir -p $EFS_MOUNT_POINT/python
                - pip3 install --target=$EFS_MOUNT_POINT/python lancedb sentence-transformers boto3
                - echo "Libraries installed"
                - echo "Step 3 - Initializing LanceDB..."
                - |
                  python3 << 'EOF'
                  import sys
                  import os
                  from datetime import datetime
                  sys.path.insert(0, os.path.join(os.environ['EFS_MOUNT_POINT'], 'python'))
                  import lancedb
                  from sentence_transformers import SentenceTransformer
                  model_name = os.environ['MODEL_NAME']
                  efs_mount = os.environ['EFS_MOUNT_POINT']
                  lancedb_path = os.path.join(efs_mount, 'suplementia-lancedb')
                  model_path = os.path.join(efs_mount, 'models', model_name)
                  print("Loading model...")
                  model = SentenceTransformer(model_path)
                  supplements = [
                      {"name": "Vitamin D", "scientific_name": "Cholecalciferol", "category": "vitamin"},
                      {"name": "Omega-3", "scientific_name": "Omega-3 Fatty Acids", "category": "fatty-acid"},
                      {"name": "Magnesium", "scientific_name": "Magnesium", "category": "mineral"},
                      {"name": "Vitamin C", "scientific_name": "Ascorbic Acid", "category": "vitamin"},
                      {"name": "Zinc", "scientific_name": "Zinc", "category": "mineral"},
                  ]
                  print("Initializing LanceDB...")
                  db = lancedb.connect(lancedb_path)
                  data = []
                  for idx, supp in enumerate(supplements, 1):
                      embedding = model.encode(supp['name']).tolist()
                      data.append({
                          'id': idx,
                          'name': supp['name'],
                          'scientific_name': supp.get('scientific_name', ''),
                          'common_names': [],
                          'vector': embedding,
                          'metadata': {
                              'category': supp.get('category', 'other'),
                              'popularity': 'high',
                              'evidence_grade': 'A',
                              'study_count': 100,
                              'pubmed_query': supp['name']
                          },
                          'search_count': 0,
                          'last_searched_at': datetime.now().isoformat(),
                          'created_at': datetime.now().isoformat(),
                          'updated_at': datetime.now().isoformat()
                      })
                  table = db.create_table('supplements', data=data, mode='overwrite')
                  print(f"Created table with {len(data)} supplements")
                  df = table.to_pandas()
                  print(f"Verification: {len(df)} records in database")
                  print(df[['id', 'name', 'scientific_name']])
                  EOF
            post_build:
              commands:
                - echo "Setup complete!"
                - echo "Verifying EFS contents..."
                - ls -lh $EFS_MOUNT_POINT/
                - du -sh $EFS_MOUNT_POINT/* || true
                - echo "✓ EFS setup successful"
      
      VpcConfig:
        VpcId: !Ref VPCId
        Subnets: !Ref PrivateSubnetIds
        SecurityGroupIds:
          - !Ref SecurityGroupId
      
      FileSystemLocations:
        - Identifier: efs1
          Location: !Sub '${EFSFileSystemId}.efs.${AWS::Region}.amazonaws.com:/'
          MountPoint: /mnt/efs
          Type: EFS
      
      TimeoutInMinutes: 60
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-efs-setup'
        - Key: Environment
          Value: !Ref Environment

Outputs:
  ProjectName:
    Description: CodeBuild project name
    Value: !Ref EFSSetupProject
  
  ProjectArn:
    Description: CodeBuild project ARN
    Value: !GetAtt EFSSetupProject.Arn
  
  Instructions:
    Description: How to run the setup
    Value: !Sub 'aws codebuild start-build --project-name ${EFSSetupProject}'
