AWSTemplateFormatVersion: '2010-09-09'
Description: 'SuplementIA - LanceDB Vector Search Stack (Production)'

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - staging
      - production
    Description: Environment name
  
  AlertEmail:
    Type: String
    Description: Email for CloudWatch alerts
    Default: alerts@suplementia.com

Resources:
  # ============================================================================
  # VPC for EFS Access
  # ============================================================================
  
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-suplementia-vpc'
  
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-private-subnet-1'
  
  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [1, !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-private-subnet-2'
  
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Lambda functions
      VpcId: !Ref VPC
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-lambda-sg'
  
  EFSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for EFS
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 2049
          ToPort: 2049
          SourceSecurityGroupId: !Ref LambdaSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-efs-sg'
  
  # ============================================================================
  # EFS for LanceDB + ML Models
  # ============================================================================
  
  EFSFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      PerformanceMode: generalPurpose
      ThroughputMode: bursting
      Encrypted: true
      FileSystemTags:
        - Key: Name
          Value: !Sub '${Environment}-suplementia-efs'
  
  EFSMountTarget1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EFSFileSystem
      SubnetId: !Ref PrivateSubnet1
      SecurityGroups:
        - !Ref EFSSecurityGroup
  
  EFSMountTarget2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EFSFileSystem
      SubnetId: !Ref PrivateSubnet2
      SecurityGroups:
        - !Ref EFSSecurityGroup
  
  EFSAccessPoint:
    Type: AWS::EFS::AccessPoint
    Properties:
      FileSystemId: !Ref EFSFileSystem
      PosixUser:
        Uid: '1000'
        Gid: '1000'
      RootDirectory:
        Path: /suplementia
        CreationInfo:
          OwnerUid: '1000'
          OwnerGid: '1000'
          Permissions: '755'
  
  # ============================================================================
  # DynamoDB Tables
  # ============================================================================
  
  SupplementCacheTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${Environment}-lancedb-supplement-cache'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-supplement-cache'
  
  DiscoveryQueueTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${Environment}-lancedb-discovery-queue'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-discovery-queue'
  
  # ============================================================================
  # IAM Roles
  # ============================================================================
  
  SearchAPILambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${Environment}-search-api-lambda-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                Resource:
                  - !GetAtt SupplementCacheTable.Arn
                  - !GetAtt DiscoveryQueueTable.Arn
        - PolicyName: EFSAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - elasticfilesystem:ClientMount
                  - elasticfilesystem:ClientWrite
                  - elasticfilesystem:ClientRootAccess
                Resource: !GetAtt EFSFileSystem.Arn
  
  DiscoveryWorkerLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${Environment}-discovery-worker-lambda-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:GetRecords
                  - dynamodb:GetShardIterator
                  - dynamodb:DescribeStream
                  - dynamodb:ListStreams
                Resource:
                  - !GetAtt SupplementCacheTable.Arn
                  - !GetAtt DiscoveryQueueTable.Arn
                  - !Sub '${DiscoveryQueueTable.Arn}/stream/*'
        - PolicyName: EFSAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - elasticfilesystem:ClientMount
                  - elasticfilesystem:ClientWrite
                  - elasticfilesystem:ClientRootAccess
                Resource: !GetAtt EFSFileSystem.Arn
  
  # ============================================================================
  # Lambda Functions
  # ============================================================================
  
  SearchAPILambda:
    Type: AWS::Lambda::Function
    DependsOn:
      - EFSMountTarget1
      - EFSMountTarget2
    Properties:
      FunctionName: !Sub '${Environment}-search-api-lancedb'
      Runtime: python3.11
      Handler: lambda_function.lambda_handler
      Role: !GetAtt SearchAPILambdaRole.Arn
      Timeout: 30
      MemorySize: 512
      Architectures:
        - arm64
      Environment:
        Variables:
          LANCEDB_PATH: /mnt/efs/suplementia-lancedb
          MODEL_PATH: /mnt/efs/models/all-MiniLM-L6-v2
          DYNAMODB_CACHE_TABLE: !Ref SupplementCacheTable
          SIMILARITY_THRESHOLD: '0.85'
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnet1
          - !Ref PrivateSubnet2
      FileSystemConfigs:
        - Arn: !GetAtt EFSAccessPoint.Arn
          LocalMountPath: /mnt/efs
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {'statusCode': 200, 'body': 'Placeholder'}
  
  DiscoveryWorkerLambda:
    Type: AWS::Lambda::Function
    DependsOn:
      - EFSMountTarget1
      - EFSMountTarget2
    Properties:
      FunctionName: !Sub '${Environment}-discovery-worker-lancedb'
      Runtime: python3.11
      Handler: lambda_function.lambda_handler
      Role: !GetAtt DiscoveryWorkerLambdaRole.Arn
      Timeout: 300
      MemorySize: 1024
      Architectures:
        - arm64
      Environment:
        Variables:
          LANCEDB_PATH: /mnt/efs/suplementia-lancedb
          MODEL_PATH: /mnt/efs/models/all-MiniLM-L6-v2
          MIN_STUDIES: '3'
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnet1
          - !Ref PrivateSubnet2
      FileSystemConfigs:
        - Arn: !GetAtt EFSAccessPoint.Arn
          LocalMountPath: /mnt/efs
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {'statusCode': 200, 'body': 'Placeholder'}
  
  DiscoveryWorkerEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt DiscoveryQueueTable.StreamArn
      FunctionName: !Ref DiscoveryWorkerLambda
      StartingPosition: LATEST
      BatchSize: 10
      MaximumBatchingWindowInSeconds: 5
  
  # ============================================================================
  # CloudWatch Alarms
  # ============================================================================
  
  AlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${Environment}-suplementia-alerts'
      Subscription:
        - Endpoint: !Ref AlertEmail
          Protocol: email
  
  SearchAPIErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${Environment}-search-api-high-errors'
      AlarmDescription: Search API error rate > 1%
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref SearchAPILambda
      AlarmActions:
        - !Ref AlertTopic
  
  SearchAPILatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${Environment}-search-api-high-latency'
      AlarmDescription: Search API P95 latency > 300ms
      MetricName: Duration
      Namespace: AWS/Lambda
      ExtendedStatistic: p95
      Period: 300
      EvaluationPeriods: 2
      Threshold: 300
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref SearchAPILambda
      AlarmActions:
        - !Ref AlertTopic

Outputs:
  EFSFileSystemId:
    Description: EFS File System ID
    Value: !Ref EFSFileSystem
    Export:
      Name: !Sub '${Environment}-efs-id'
  
  SearchAPILambdaArn:
    Description: Search API Lambda ARN
    Value: !GetAtt SearchAPILambda.Arn
    Export:
      Name: !Sub '${Environment}-search-api-arn'
  
  SupplementCacheTableName:
    Description: DynamoDB Cache Table Name
    Value: !Ref SupplementCacheTable
    Export:
      Name: !Sub '${Environment}-cache-table'
  
  TotalMonthlyCost:
    Description: Estimated monthly cost
    Value: '$5.59/month (DynamoDB $0.39 + EFS $4.00 + CloudWatch $1.20)'
