AWSTemplateFormatVersion: '2010-09-09'
Description: 'Suplementia Production Stack - New Account (Cost Optimized, ARM64, LanceDB)'

Parameters:
  Environment:
    Type: String
    Default: production
    Description: Environment name
    AllowedValues:
      - production
      - staging

Resources:
  # ==================== NETWORKING ====================
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-suplementia-vpc'
        - Key: Environment
          Value: !Ref Environment
        - Key: CostOptimized
          Value: 'true'

  # Private Subnets for Lambda & EFS
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.10.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-private-subnet-1'

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.11.0/24
      AvailabilityZone: !Select [1, !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-private-subnet-2'

  # ==================== SECURITY GROUPS ====================
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Lambda functions
      VpcId: !Ref VPC
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-lambda-sg'

  EFSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for EFS
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 2049
          ToPort: 2049
          SourceSecurityGroupId: !Ref LambdaSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-efs-sg'

  # ==================== DYNAMODB TABLES (for imported data) ====================
  SupplementCacheTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${Environment}-supplement-cache'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: searchQuery
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: search-query-index
          KeySchema:
            - AttributeName: searchQuery
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: ttl
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-supplement-cache'
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: 'Primary cache from LanceDB'
        - Key: CostOptimized
          Value: 'true'

  DiscoveryQueueTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${Environment}-discovery-queue'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: priority
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: priority-index
          KeySchema:
            - AttributeName: priority
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-discovery-queue'
        - Key: Environment
          Value: !Ref Environment

  LanceDBSupplementCacheTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${Environment}-lancedb-supplement-cache'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: ttl
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-lancedb-supplement-cache'
        - Key: Environment
          Value: !Ref Environment

  LanceDBDiscoveryQueueTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${Environment}-lancedb-discovery-queue'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: ttl
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-lancedb-discovery-queue'
        - Key: Environment
          Value: !Ref Environment

  SupplementiaContentEnricherCacheTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: suplementia-content-enricher-cache
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: ttl
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Name
          Value: suplementia-content-enricher-cache
        - Key: Environment
          Value: !Ref Environment

  # ==================== EFS for LanceDB ====================
  EFSFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true
      PerformanceMode: generalPurpose
      ThroughputMode: bursting
      FileSystemTags:
        - Key: Name
          Value: !Sub '${Environment}-lancedb-data'
        - Key: Environment
          Value: !Ref Environment

  EFSMountTarget1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EFSFileSystem
      SubnetId: !Ref PrivateSubnet1
      SecurityGroups:
        - !Ref EFSSecurityGroup

  EFSMountTarget2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EFSFileSystem
      SubnetId: !Ref PrivateSubnet2
      SecurityGroups:
        - !Ref EFSSecurityGroup

  EFSAccessPoint:
    Type: AWS::EFS::AccessPoint
    Properties:
      FileSystemId: !Ref EFSFileSystem
      PosixUser:
        Uid: '1000'
        Gid: '1000'
      RootDirectory:
        Path: /lancedb
        CreationInfo:
          OwnerUid: '1000'
          OwnerGid: '1000'
          Permissions: '755'

  # ==================== IAM ROLES ====================
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${Environment}-suplementia-lambda-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:DeleteItem
                  - dynamodb:BatchGetItem
                  - dynamodb:BatchWriteItem
                  - dynamodb:DescribeStream
                  - dynamodb:GetRecords
                  - dynamodb:GetShardIterator
                  - dynamodb:ListStreams
                Resource:
                  - !GetAtt SupplementCacheTable.Arn
                  - !Sub '${SupplementCacheTable.Arn}/index/*'
                  - !GetAtt DiscoveryQueueTable.Arn
                  - !Sub '${DiscoveryQueueTable.Arn}/index/*'
                  - !GetAtt LanceDBSupplementCacheTable.Arn
                  - !GetAtt LanceDBDiscoveryQueueTable.Arn
                  - !GetAtt SupplementiaContentEnricherCacheTable.Arn
        - PolicyName: EFSAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - elasticfilesystem:ClientMount
                  - elasticfilesystem:ClientWrite
                  - elasticfilesystem:ClientRead
                Resource: !GetAtt EFSFileSystem.Arn
              - Effect: Allow
                Action:
                  - elasticfilesystem:DescribeMountTargets
                Resource: '*'
        - PolicyName: BedrockAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                Resource: '*'
        - PolicyName: CloudWatchMetrics
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                Resource: '*'
        - PolicyName: XRayAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - xray:PutTraceSegments
                  - xray:PutTelemetryRecords
                Resource: '*'
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: '*'

  # ==================== CLOUDWATCH LOGS ====================
  SearchAPILogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${Environment}-search-api-lancedb'
      RetentionInDays: 7

  StudiesFetcherLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${Environment}-studies-fetcher'
      RetentionInDays: 7

  ContentEnricherLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${Environment}-content-enricher'
      RetentionInDays: 7

  DiscoveryWorkerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${Environment}-discovery-worker-lancedb'
      RetentionInDays: 7

  # ==================== CLOUDWATCH ALARMS ====================
  HighErrorRateAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${Environment}-suplementia-high-error-rate'
      AlarmDescription: Alert when Lambda error rate exceeds threshold
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching

  HighLatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${Environment}-suplementia-high-latency'
      AlarmDescription: Alert when P95 latency exceeds 300ms
      MetricName: Duration
      Namespace: AWS/Lambda
      ExtendedStatistic: p95
      Period: 300
      EvaluationPeriods: 2
      Threshold: 300
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching

  # ==================== ROUTE53 DNS ====================
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: suplementai.com
      HostedZoneConfig:
        Comment: Hosted zone for suplementai.com
      Tags:
        - Key: Name
          Value: suplementai-hosted-zone
        - Key: Environment
          Value: !Ref Environment

  # ==================== SNS ALERTS ====================
  AlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${Environment}-suplementia-alerts'
      DisplayName: Suplementia Alerts
      Tags:
        - Key: Environment
          Value: !Ref Environment

Outputs:
  VPCId:
    Description: VPC ID
    Value: !Ref VPC
    Export:
      Name: !Sub '${Environment}-suplementia-VPCId'

  PrivateSubnet1Id:
    Description: Private Subnet 1 ID
    Value: !Ref PrivateSubnet1
    Export:
      Name: !Sub '${Environment}-suplementia-PrivateSubnet1'

  PrivateSubnet2Id:
    Description: Private Subnet 2 ID
    Value: !Ref PrivateSubnet2
    Export:
      Name: !Sub '${Environment}-suplementia-PrivateSubnet2'

  LambdaSecurityGroupId:
    Description: Lambda Security Group ID
    Value: !Ref LambdaSecurityGroup
    Export:
      Name: !Sub '${Environment}-suplementia-LambdaSecurityGroup'

  EFSFileSystemId:
    Description: EFS File System ID for LanceDB
    Value: !Ref EFSFileSystem
    Export:
      Name: !Sub '${Environment}-suplementia-EFSFileSystemId'

  EFSAccessPointId:
    Description: EFS Access Point ID
    Value: !Ref EFSAccessPoint
    Export:
      Name: !Sub '${Environment}-suplementia-EFSAccessPointId'

  SupplementCacheTableName:
    Description: DynamoDB Supplement Cache Table Name
    Value: !Ref SupplementCacheTable
    Export:
      Name: !Sub '${Environment}-suplementia-SupplementCacheTable'

  DiscoveryQueueTableName:
    Description: DynamoDB Discovery Queue Table Name
    Value: !Ref DiscoveryQueueTable
    Export:
      Name: !Sub '${Environment}-suplementia-DiscoveryQueueTable'

  LanceDBSupplementCacheTableName:
    Description: DynamoDB LanceDB Supplement Cache Table
    Value: !Ref LanceDBSupplementCacheTable
    Export:
      Name: !Sub '${Environment}-suplementia-LanceDBSupplementCacheTable'

  LanceDBDiscoveryQueueTableName:
    Description: DynamoDB LanceDB Discovery Queue Table
    Value: !Ref LanceDBDiscoveryQueueTable
    Export:
      Name: !Sub '${Environment}-suplementia-LanceDBDiscoveryQueueTable'

  ContentEnricherCacheTableName:
    Description: DynamoDB Content Enricher Cache Table
    Value: !Ref SupplementiaContentEnricherCacheTable
    Export:
      Name: !Sub '${Environment}-suplementia-ContentEnricherCacheTable'

  LambdaExecutionRoleArn:
    Description: Lambda Execution Role ARN
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: !Sub '${Environment}-suplementia-LambdaExecutionRoleArn'

  AlertTopicArn:
    Description: SNS Topic ARN for Alerts
    Value: !Ref AlertTopic
    Export:
      Name: !Sub '${Environment}-suplementia-AlertTopicArn'

  HostedZoneId:
    Description: Route53 Hosted Zone ID for suplementai.com
    Value: !Ref HostedZone
    Export:
      Name: !Sub '${Environment}-suplementai-HostedZoneId'

  NameServers:
    Description: Route53 NameServers for suplementai.com - Add these to Namecheap
    Value: !Join
      - ', '
      - !GetAtt HostedZone.NameServers

  StackStatus:
    Description: Stack deployment status
    Value: 'Optimized for cost, ready for Lambda deployment and DynamoDB data import'
