AWSTemplateFormatVersion: '2010-09-09'
Description: 'Portal Subscriptions Table - Stores user subscription status'

Parameters:
  Environment:
    Type: String
    Default: staging
    AllowedValues:
      - staging
      - production
    Description: Environment name

Resources:
  PortalSubscriptionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'ankosoft-portal-subscriptions-${Environment}'
      BillingMode: PAY_PER_REQUEST
      
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: stripe_subscription_id
          AttributeType: S
      
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      
      GlobalSecondaryIndexes:
        - IndexName: stripe-subscription-id-index
          KeySchema:
            - AttributeName: stripe_subscription_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      
      Tags:
        - Key: Project
          Value: AnkoSoft
        - Key: Component
          Value: EducationPortal
        - Key: Environment
          Value: !Ref Environment

Outputs:
  PortalSubscriptionsTableName:
    Description: Portal Subscriptions Table Name
    Value: !Ref PortalSubscriptionsTable
    Export:
      Name: !Sub '${AWS::StackName}-PortalSubscriptionsTable'

