AWSTemplateFormatVersion: '2010-09-09'
Description: 'Portal Cognito User Pool for Public User Authentication'

Parameters:
  Environment:
    Type: String
    Default: staging
    AllowedValues:
      - staging
      - production
    Description: Environment name

Resources:
  PortalUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub 'ankosoft-portal-users-${Environment}'
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
      Schema:
        - Name: email
          Required: true
          Mutable: true
        - Name: name
          Required: false
          Mutable: true
        - Name: locale
          Required: false
          Mutable: true
      MfaConfiguration: OPTIONAL
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      Tags:
        - Key: Project
          Value: AnkoSoft
        - Key: Component
          Value: EducationPortal
        - Key: Environment
          Value: !Ref Environment

  PortalUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref PortalUserPool
      ClientName: !Sub 'portal-web-client-${Environment}'
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      PreventUserExistenceErrors: ENABLED
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days
      AccessTokenValidity: 1
      IdTokenValidity: 1
      RefreshTokenValidity: 30

  PortalIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: !Sub 'ankosoft-portal-identity-${Environment}'
      AllowUnauthenticatedIdentities: true
      CognitoIdentityProviders:
        - ClientId: !Ref PortalUserPoolClient
          ProviderName: !GetAtt PortalUserPool.ProviderName

Outputs:
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref PortalUserPool
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolId'
  
  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref PortalUserPoolClient
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolClientId'
  
  IdentityPoolId:
    Description: Cognito Identity Pool ID
    Value: !Ref PortalIdentityPool
    Export:
      Name: !Sub '${AWS::StackName}-IdentityPoolId'

