AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Studies Fetcher Lambda - Fetch real scientific studies from PubMed

Globals:
  Function:
    Timeout: 60
    MemorySize: 1024
    Runtime: nodejs20.x
    Architectures:
      - arm64
    Tracing: Active
    Environment:
      Variables:
        NODE_OPTIONS: --enable-source-maps
        XRAY_ENABLED: 'true'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name

  PubMedApiKey:
    Type: String
    Default: ''
    Description: Optional PubMed API key for higher rate limits
    NoEcho: true

  CacheServiceUrl:
    Type: String
    Default: ''
    Description: Optional URL for cache service integration

  DefaultMaxResults:
    Type: Number
    Default: 10
    MinValue: 1
    MaxValue: 100
    Description: Default maximum number of results to return

  DefaultYearFrom:
    Type: Number
    Default: 2010
    Description: Default year filter for studies

Resources:
  # Lambda Function
  StudiesFetcherFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub suplementia-studies-fetcher-${Environment}
      CodeUri: dist/
      Handler: index.handler
      Description: Fetch real scientific studies from PubMed
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          PUBMED_API_KEY: !Ref PubMedApiKey
          CACHE_SERVICE_URL: !Ref CacheServiceUrl
          DEFAULT_MAX_RESULTS: !Ref DefaultMaxResults
          DEFAULT_YEAR_FROM: !Ref DefaultYearFrom
          LOG_LEVEL: info
          # Intelligent ranking feature flags (enabled by default)
          USE_INTELLIGENT_SEARCH: 'true'
          USE_INTELLIGENT_RANKING: 'true'
      Events:
        SearchStudies:
          Type: Api
          Properties:
            Path: /studies/search
            Method: POST
            RestApiId: !Ref StudiesFetcherApi
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/suplementia-studies-fetcher-${Environment}:*
            - Effect: Allow
              Action:
                - xray:PutTraceSegments
                - xray:PutTelemetryRecords
              Resource: '*'
            # Bedrock permissions for intelligent ranking (Claude Haiku for sentiment analysis)
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource:
                - !Sub arn:aws:bedrock:${AWS::Region}::foundation-model/anthropic.claude-3-haiku-20240307-v1:0
                - !Sub arn:aws:bedrock:${AWS::Region}::foundation-model/anthropic.claude-3-5-haiku-*
      Tags:
        Project: Suplementia
        Module: StudiesFetcher
        Environment: !Ref Environment

  # API Gateway
  StudiesFetcherApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub suplementia-studies-api-${Environment}
      StageName: !Ref Environment
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'Content-Type,X-Request-ID'"
        AllowMethods: "'POST,OPTIONS'"
      TracingEnabled: true
      MethodSettings:
        - ResourcePath: '/*'
          HttpMethod: '*'
          LoggingLevel: INFO
          DataTraceEnabled: true
          MetricsEnabled: true
      Tags:
        Project: Suplementia
        Module: StudiesFetcher
        Environment: !Ref Environment

  # CloudWatch Log Group
  StudiesFetcherLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/suplementia-studies-fetcher-${Environment}
      RetentionInDays: 30

  # CloudWatch Alarms
  StudiesFetcherErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub suplementia-studies-fetcher-errors-${Environment}
      AlarmDescription: Alert when Studies Fetcher has errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref StudiesFetcherFunction
      TreatMissingData: notBreaching

  StudiesFetcherThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub suplementia-studies-fetcher-throttles-${Environment}
      AlarmDescription: Alert when Studies Fetcher is throttled
      MetricName: Throttles
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 3
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref StudiesFetcherFunction
      TreatMissingData: notBreaching

  StudiesFetcherDurationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub suplementia-studies-fetcher-duration-${Environment}
      AlarmDescription: Alert when Studies Fetcher takes too long
      MetricName: Duration
      Namespace: AWS/Lambda
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 55000  # 55 seconds (timeout is 60s)
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref StudiesFetcherFunction
      TreatMissingData: notBreaching

Outputs:
  StudiesFetcherFunctionArn:
    Description: ARN of the Studies Fetcher Lambda function
    Value: !GetAtt StudiesFetcherFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-FunctionArn

  StudiesFetcherApiUrl:
    Description: URL of the Studies Fetcher API
    Value: !Sub https://${StudiesFetcherApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/studies/search
    Export:
      Name: !Sub ${AWS::StackName}-ApiUrl

  StudiesFetcherApiId:
    Description: API Gateway ID
    Value: !Ref StudiesFetcherApi
    Export:
      Name: !Sub ${AWS::StackName}-ApiId
