/**
 * Supplements Database for Autocomplete
 * Rich database of nutraceuticals, herbs, vitamins, minerals, and health conditions
 * Supports fuzzy search with Fuse.js
 */

export interface SupplementEntry {
  id: string;
  name: string;
  aliases: string[]; // Alternative names, common typos
  category: 'herb' | 'vitamin' | 'mineral' | 'amino-acid' | 'fatty-acid' | 'other' | 'condition';
  healthConditions?: string[]; // Related health conditions
  language: 'es' | 'en';
}

/**
 * Database of supplements, herbs, and health conditions
 * Includes common typos and variations for better fuzzy matching
 */
export const SUPPLEMENTS_DATABASE: SupplementEntry[] = [
  // ===== HIERBAS ADAPTÓGENAS (Español) =====
  {
    id: 'ashwagandha-es',
    name: 'Ashwagandha',
    aliases: ['ashwaghanda', 'ashvagandha', 'withania somnifera', 'ginseng indio'],
    category: 'herb',
    healthConditions: ['estrés', 'ansiedad', 'sueño', 'cortisol', 'energía'],
    language: 'es',
  },
  {
    id: 'rhodiola-es',
    name: 'Rhodiola',
    aliases: ['rhodiola rosea', 'rodiola', 'raíz dorada', 'raiz de oro'],
    category: 'herb',
    healthConditions: ['fatiga', 'energía', 'resistencia', 'estrés'],
    language: 'es',
  },
  {
    id: 'ginseng-es',
    name: 'Ginseng',
    aliases: ['ginseng coreano', 'panax ginseng', 'ginseng rojo'],
    category: 'herb',
    healthConditions: ['energía', 'cognición', 'memoria', 'inmunidad'],
    language: 'es',
  },
  {
    id: 'maca-es',
    name: 'Maca',
    aliases: ['maca peruana', 'lepidium meyenii'],
    category: 'herb',
    healthConditions: ['energía', 'libido', 'fertilidad', 'resistencia'],
    language: 'es',
  },
  {
    id: 'turmeric-es',
    name: 'Cúrcuma',
    aliases: ['curcuma', 'turmeric', 'curcumina'],
    category: 'herb',
    healthConditions: ['inflamación', 'articulaciones', 'digestión'],
    language: 'es',
  },

  // ===== HIERBAS PARA EL SUEÑO (Español) =====
  {
    id: 'melatonin-es',
    name: 'Melatonina',
    aliases: ['melatonina', 'hormona del sueño'],
    category: 'other',
    healthConditions: ['sueño', 'insomnio', 'jet lag', 'ritmo circadiano'],
    language: 'es',
  },
  {
    id: 'valerian-es',
    name: 'Valeriana',
    aliases: ['valerian', 'valeriana officinalis'],
    category: 'herb',
    healthConditions: ['sueño', 'ansiedad', 'relajación'],
    language: 'es',
  },
  {
    id: 'chamomile-es',
    name: 'Manzanilla',
    aliases: ['camomila', 'chamomile', 'té de manzanilla'],
    category: 'herb',
    healthConditions: ['sueño', 'digestión', 'relajación', 'ansiedad'],
    language: 'es',
  },

  // ===== VITAMINAS (Español) =====
  {
    id: 'vitamin-d-es',
    name: 'Vitamina D',
    aliases: ['vitamina d3', 'colecalciferol', 'vitamina del sol'],
    category: 'vitamin',
    healthConditions: ['huesos', 'inmunidad', 'ánimo', 'deficiencia vitamina d'],
    language: 'es',
  },
  {
    id: 'vitamin-c-es',
    name: 'Vitamina C',
    aliases: ['ácido ascórbico', 'acido ascorbico'],
    category: 'vitamin',
    healthConditions: ['inmunidad', 'antioxidante', 'colágeno', 'resfriado'],
    language: 'es',
  },
  {
    id: 'vitamin-b12-es',
    name: 'Vitamina B12',
    aliases: ['b12', 'cobalamina', 'cianocobalamina'],
    category: 'vitamin',
    healthConditions: ['energía', 'nervios', 'anemia', 'veganos'],
    language: 'es',
  },
  {
    id: 'vitamin-b1-es',
    name: 'Vitamina B1',
    aliases: ['b1', 'tiamina', 'thiamine'],
    category: 'vitamin',
    healthConditions: ['energía', 'nervios', 'metabolismo'],
    language: 'es',
  },
  {
    id: 'vitamin-b2-es',
    name: 'Vitamina B2',
    aliases: ['b2', 'riboflavina', 'riboflavin'],
    category: 'vitamin',
    healthConditions: ['energía', 'piel', 'ojos', 'migrañas'],
    language: 'es',
  },
  {
    id: 'vitamin-b3-es',
    name: 'Vitamina B3',
    aliases: ['b3', 'niacina', 'niacin', 'acido nicotinico'],
    category: 'vitamin',
    healthConditions: ['colesterol', 'energía', 'piel'],
    language: 'es',
  },
  {
    id: 'vitamin-b5-es',
    name: 'Vitamina B5',
    aliases: ['b5', 'acido pantotenico', 'pantothenic acid'],
    category: 'vitamin',
    healthConditions: ['energía', 'hormonas', 'estrés'],
    language: 'es',
  },
  {
    id: 'vitamin-b6-es',
    name: 'Vitamina B6',
    aliases: ['b6', 'piridoxina', 'pyridoxine'],
    category: 'vitamin',
    healthConditions: ['ánimo', 'sueño', 'nervios', 'náuseas'],
    language: 'es',
  },
  {
    id: 'vitamin-b7-es',
    name: 'Vitamina B7',
    aliases: ['b7', 'biotina', 'biotin', 'vitamina h'],
    category: 'vitamin',
    healthConditions: ['cabello', 'uñas', 'piel'],
    language: 'es',
  },
  {
    id: 'vitamin-b9-es',
    name: 'Vitamina B9',
    aliases: ['b9', 'acido folico', 'folato', 'folate'],
    category: 'vitamin',
    healthConditions: ['embarazo', 'anemia', 'corazón'],
    language: 'es',
  },
  {
    id: 'vitamin-k2-es',
    name: 'Vitamina K2',
    aliases: ['k2', 'menaquinona'],
    category: 'vitamin',
    healthConditions: ['huesos', 'corazón', 'calcio'],
    language: 'es',
  },

  // ===== MINERALES (Español) =====
  {
    id: 'magnesium-es',
    name: 'Magnesio',
    aliases: ['magnesio', 'citrato de magnesio', 'glicinato de magnesio'],
    category: 'mineral',
    healthConditions: ['sueño', 'músculos', 'calambres', 'estrés', 'energía'],
    language: 'es',
  },
  {
    id: 'zinc-es',
    name: 'Zinc',
    aliases: ['zinc', 'picolinato de zinc'],
    category: 'mineral',
    healthConditions: ['inmunidad', 'testosterona', 'piel', 'acné'],
    language: 'es',
  },
  {
    id: 'iron-es',
    name: 'Hierro',
    aliases: ['hierro', 'sulfato ferroso', 'bisglicinato de hierro'],
    category: 'mineral',
    healthConditions: ['anemia', 'energía', 'fatiga', 'hemoglobina'],
    language: 'es',
  },
  {
    id: 'calcium-es',
    name: 'Calcio',
    aliases: ['calcio', 'carbonato de calcio'],
    category: 'mineral',
    healthConditions: ['huesos', 'osteoporosis', 'dientes'],
    language: 'es',
  },

  // ===== ÁCIDOS GRASOS (Español) =====
  {
    id: 'omega3-es',
    name: 'Omega-3',
    aliases: ['omega 3', 'aceite de pescado', 'epa', 'dha', 'fish oil'],
    category: 'fatty-acid',
    healthConditions: ['corazón', 'cerebro', 'inflamación', 'triglicéridos'],
    language: 'es',
  },
  {
    id: 'fish-oil-es',
    name: 'Aceite de Pescado',
    aliases: ['fish oil', 'omega-3', 'aceite de salmon'],
    category: 'fatty-acid',
    healthConditions: ['corazón', 'cerebro', 'colesterol'],
    language: 'es',
  },

  // ===== AMINOÁCIDOS Y OTROS (Español) =====
  {
    id: 'creatine-es',
    name: 'Creatina',
    aliases: ['creatina monohidrato', 'creatine'],
    category: 'amino-acid',
    healthConditions: ['músculo', 'fuerza', 'rendimiento', 'ejercicio'],
    language: 'es',
  },
  {
    id: 'protein-es',
    name: 'Proteína Whey',
    aliases: ['whey protein', 'proteina de suero', 'suero de leche'],
    category: 'amino-acid',
    healthConditions: ['músculo', 'recuperación', 'masa muscular'],
    language: 'es',
  },
  {
    id: 'collagen-es',
    name: 'Colágeno',
    aliases: ['colageno', 'collagen', 'colágeno hidrolizado'],
    category: 'other',
    healthConditions: ['piel', 'articulaciones', 'pelo', 'uñas'],
    language: 'es',
  },
  {
    id: 'cbd-es',
    name: 'CBD',
    aliases: ['cannabidiol', 'aceite de cbd', 'cbd oil'],
    category: 'other',
    healthConditions: ['dolor', 'ansiedad', 'inflamación', 'sueño'],
    language: 'es',
  },
  {
    id: 'probiotics-es',
    name: 'Probióticos',
    aliases: ['probioticos', 'flora intestinal', 'bacterias buenas'],
    category: 'other',
    healthConditions: ['digestión', 'intestino', 'inmunidad', 'microbiota'],
    language: 'es',
  },

  // ===== CONDICIONES DE SALUD (Español) =====
  {
    id: 'sleep-condition-es',
    name: 'Mejorar sueño',
    aliases: ['insomnio', 'dormir mejor', 'calidad del sueño'],
    category: 'condition',
    language: 'es',
  },
  {
    id: 'anxiety-condition-es',
    name: 'Reducir ansiedad',
    aliases: ['estrés', 'nervios', 'calma', 'relajación'],
    category: 'condition',
    language: 'es',
  },
  {
    id: 'energy-condition-es',
    name: 'Aumentar energía',
    aliases: ['fatiga', 'cansancio', 'vitalidad'],
    category: 'condition',
    language: 'es',
  },
  {
    id: 'muscle-condition-es',
    name: 'Ganar músculo',
    aliases: ['masa muscular', 'hipertrofia', 'bodybuilding'],
    category: 'condition',
    language: 'es',
  },
  {
    id: 'immunity-condition-es',
    name: 'Fortalecer inmunidad',
    aliases: ['defensas', 'sistema inmune', 'prevenir resfriados'],
    category: 'condition',
    language: 'es',
  },

  // ===== ADAPTOGENIC HERBS (English) =====
  {
    id: 'ashwagandha-en',
    name: 'Ashwagandha',
    aliases: ['ashwaghanda', 'ashvagandha', 'withania somnifera', 'indian ginseng'],
    category: 'herb',
    healthConditions: ['stress', 'anxiety', 'sleep', 'cortisol', 'energy'],
    language: 'en',
  },
  {
    id: 'rhodiola-en',
    name: 'Rhodiola',
    aliases: ['rhodiola rosea', 'golden root', 'arctic root'],
    category: 'herb',
    healthConditions: ['fatigue', 'energy', 'endurance', 'stress'],
    language: 'en',
  },
  {
    id: 'ginseng-en',
    name: 'Ginseng',
    aliases: ['korean ginseng', 'panax ginseng', 'red ginseng'],
    category: 'herb',
    healthConditions: ['energy', 'cognition', 'memory', 'immunity'],
    language: 'en',
  },
  {
    id: 'maca-en',
    name: 'Maca',
    aliases: ['peruvian maca', 'lepidium meyenii'],
    category: 'herb',
    healthConditions: ['energy', 'libido', 'fertility', 'endurance'],
    language: 'en',
  },
  {
    id: 'turmeric-en',
    name: 'Turmeric',
    aliases: ['curcumin', 'turmeric root'],
    category: 'herb',
    healthConditions: ['inflammation', 'joints', 'digestion'],
    language: 'en',
  },

  // ===== SLEEP HERBS (English) =====
  {
    id: 'melatonin-en',
    name: 'Melatonin',
    aliases: ['sleep hormone'],
    category: 'other',
    healthConditions: ['sleep', 'insomnia', 'jet lag', 'circadian rhythm'],
    language: 'en',
  },
  {
    id: 'valerian-en',
    name: 'Valerian',
    aliases: ['valerian root', 'valeriana officinalis'],
    category: 'herb',
    healthConditions: ['sleep', 'anxiety', 'relaxation'],
    language: 'en',
  },
  {
    id: 'chamomile-en',
    name: 'Chamomile',
    aliases: ['chamomile tea'],
    category: 'herb',
    healthConditions: ['sleep', 'digestion', 'relaxation', 'anxiety'],
    language: 'en',
  },

  // ===== VITAMINS (English) =====
  {
    id: 'vitamin-d-en',
    name: 'Vitamin D',
    aliases: ['vitamin d3', 'cholecalciferol', 'sunshine vitamin'],
    category: 'vitamin',
    healthConditions: ['bones', 'immunity', 'mood', 'vitamin d deficiency'],
    language: 'en',
  },
  {
    id: 'vitamin-c-en',
    name: 'Vitamin C',
    aliases: ['ascorbic acid'],
    category: 'vitamin',
    healthConditions: ['immunity', 'antioxidant', 'collagen', 'cold'],
    language: 'en',
  },
  {
    id: 'vitamin-b12-en',
    name: 'Vitamin B12',
    aliases: ['b12', 'cobalamin', 'cyanocobalamin'],
    category: 'vitamin',
    healthConditions: ['energy', 'nerves', 'anemia', 'vegans'],
    language: 'en',
  },
  {
    id: 'vitamin-b1-en',
    name: 'Vitamin B1',
    aliases: ['b1', 'thiamine', 'thiamin'],
    category: 'vitamin',
    healthConditions: ['energy', 'nerves', 'metabolism'],
    language: 'en',
  },
  {
    id: 'vitamin-b2-en',
    name: 'Vitamin B2',
    aliases: ['b2', 'riboflavin'],
    category: 'vitamin',
    healthConditions: ['energy', 'skin', 'eyes', 'migraines'],
    language: 'en',
  },
  {
    id: 'vitamin-b3-en',
    name: 'Vitamin B3',
    aliases: ['b3', 'niacin', 'nicotinic acid'],
    category: 'vitamin',
    healthConditions: ['cholesterol', 'energy', 'skin'],
    language: 'en',
  },
  {
    id: 'vitamin-b5-en',
    name: 'Vitamin B5',
    aliases: ['b5', 'pantothenic acid'],
    category: 'vitamin',
    healthConditions: ['energy', 'hormones', 'stress'],
    language: 'en',
  },
  {
    id: 'vitamin-b6-en',
    name: 'Vitamin B6',
    aliases: ['b6', 'pyridoxine'],
    category: 'vitamin',
    healthConditions: ['mood', 'sleep', 'nerves', 'nausea'],
    language: 'en',
  },
  {
    id: 'vitamin-b7-en',
    name: 'Vitamin B7',
    aliases: ['b7', 'biotin', 'vitamin h'],
    category: 'vitamin',
    healthConditions: ['hair', 'nails', 'skin'],
    language: 'en',
  },
  {
    id: 'vitamin-b9-en',
    name: 'Vitamin B9',
    aliases: ['b9', 'folic acid', 'folate'],
    category: 'vitamin',
    healthConditions: ['pregnancy', 'anemia', 'heart'],
    language: 'en',
  },
  {
    id: 'vitamin-k2-en',
    name: 'Vitamin K2',
    aliases: ['k2', 'menaquinone'],
    category: 'vitamin',
    healthConditions: ['bones', 'heart', 'calcium'],
    language: 'en',
  },

  // ===== MINERALS (English) =====
  {
    id: 'magnesium-en',
    name: 'Magnesium',
    aliases: ['magnesium citrate', 'magnesium glycinate'],
    category: 'mineral',
    healthConditions: ['sleep', 'muscles', 'cramps', 'stress', 'energy'],
    language: 'en',
  },
  {
    id: 'zinc-en',
    name: 'Zinc',
    aliases: ['zinc picolinate'],
    category: 'mineral',
    healthConditions: ['immunity', 'testosterone', 'skin', 'acne'],
    language: 'en',
  },
  {
    id: 'iron-en',
    name: 'Iron',
    aliases: ['ferrous sulfate', 'iron bisglycinate'],
    category: 'mineral',
    healthConditions: ['anemia', 'energy', 'fatigue', 'hemoglobin'],
    language: 'en',
  },
  {
    id: 'calcium-en',
    name: 'Calcium',
    aliases: ['calcium carbonate'],
    category: 'mineral',
    healthConditions: ['bones', 'osteoporosis', 'teeth'],
    language: 'en',
  },

  // ===== FATTY ACIDS (English) =====
  {
    id: 'omega3-en',
    name: 'Omega-3',
    aliases: ['omega 3', 'fish oil', 'epa', 'dha'],
    category: 'fatty-acid',
    healthConditions: ['heart', 'brain', 'inflammation', 'triglycerides'],
    language: 'en',
  },
  {
    id: 'fish-oil-en',
    name: 'Fish Oil',
    aliases: ['omega-3', 'salmon oil'],
    category: 'fatty-acid',
    healthConditions: ['heart', 'brain', 'cholesterol'],
    language: 'en',
  },

  // ===== AMINO ACIDS AND OTHERS (English) =====
  {
    id: 'creatine-en',
    name: 'Creatine',
    aliases: ['creatine monohydrate'],
    category: 'amino-acid',
    healthConditions: ['muscle', 'strength', 'performance', 'exercise'],
    language: 'en',
  },
  {
    id: 'protein-en',
    name: 'Whey Protein',
    aliases: ['whey', 'protein powder'],
    category: 'amino-acid',
    healthConditions: ['muscle', 'recovery', 'muscle mass'],
    language: 'en',
  },
  {
    id: 'collagen-en',
    name: 'Collagen',
    aliases: ['hydrolyzed collagen', 'collagen peptides'],
    category: 'other',
    healthConditions: ['skin', 'joints', 'hair', 'nails'],
    language: 'en',
  },
  {
    id: 'cbd-en',
    name: 'CBD',
    aliases: ['cannabidiol', 'cbd oil'],
    category: 'other',
    healthConditions: ['pain', 'anxiety', 'inflammation', 'sleep'],
    language: 'en',
  },
  {
    id: 'probiotics-en',
    name: 'Probiotics',
    aliases: ['gut flora', 'good bacteria'],
    category: 'other',
    healthConditions: ['digestion', 'gut', 'immunity', 'microbiome'],
    language: 'en',
  },

  // ===== MEDICINAL MUSHROOMS (Español) =====
  {
    id: 'reishi-es',
    name: 'Reishi',
    aliases: ['ganoderma lucidum', 'lingzhi', 'hongo reishi', 'ganoderma'],
    category: 'herb',
    healthConditions: ['inmunidad', 'estrés', 'inflamación', 'sueño', 'adaptógeno'],
    language: 'es',
  },
  {
    id: 'lions-mane-es',
    name: 'Melena de León',
    aliases: ['lions mane', 'hericium erinaceus', 'melena leon', 'hericium'],
    category: 'herb',
    healthConditions: ['memoria', 'cognición', 'nervios', 'concentración', 'neuroprotección'],
    language: 'es',
  },
  {
    id: 'chaga-es',
    name: 'Chaga',
    aliases: ['inonotus obliquus', 'hongo chaga'],
    category: 'herb',
    healthConditions: ['antioxidante', 'inmunidad', 'inflamación', 'energía'],
    language: 'es',
  },
  {
    id: 'cordyceps-es',
    name: 'Cordyceps',
    aliases: ['cordyceps sinensis', 'hongo cordyceps'],
    category: 'herb',
    healthConditions: ['energía', 'resistencia', 'rendimiento', 'libido', 'respiración'],
    language: 'es',
  },
  {
    id: 'turkey-tail-es',
    name: 'Cola de Pavo',
    aliases: ['turkey tail', 'trametes versicolor', 'coriolus'],
    category: 'herb',
    healthConditions: ['inmunidad', 'digestión', 'antioxidante', 'microbiota'],
    language: 'es',
  },
  {
    id: 'shiitake-es',
    name: 'Shiitake',
    aliases: ['lentinula edodes', 'hongo shiitake'],
    category: 'herb',
    healthConditions: ['inmunidad', 'colesterol', 'corazón'],
    language: 'es',
  },
  {
    id: 'maitake-es',
    name: 'Maitake',
    aliases: ['grifola frondosa', 'hongo maitake'],
    category: 'herb',
    healthConditions: ['inmunidad', 'azúcar en sangre', 'peso'],
    language: 'es',
  },

  // ===== ADDITIONAL POPULAR SUPPLEMENTS (Español) =====
  {
    id: 'coenzyme-q10-es',
    name: 'Coenzima Q10',
    aliases: ['coq10', 'ubiquinona', 'coenzyme q10'],
    category: 'other',
    healthConditions: ['corazón', 'energía', 'antioxidante'],
    language: 'es',
  },
  {
    id: 'collagen-es',
    name: 'Colágeno',
    aliases: ['colageno', 'collagen', 'colágeno hidrolizado'],
    category: 'other',
    healthConditions: ['piel', 'articulaciones', 'cabello', 'uñas'],
    language: 'es',
  },
  {
    id: 'biotin-es',
    name: 'Biotina',
    aliases: ['biotin', 'vitamina b7', 'vitamina h'],
    category: 'vitamin',
    healthConditions: ['cabello', 'uñas', 'piel'],
    language: 'es',
  },
  {
    id: 'folic-acid-es',
    name: 'Ácido Fólico',
    aliases: ['acido folico', 'folato', 'vitamina b9'],
    category: 'vitamin',
    healthConditions: ['embarazo', 'anemia', 'corazón'],
    language: 'es',
  },
  {
    id: 'vitamin-e-es',
    name: 'Vitamina E',
    aliases: ['tocoferol', 'vitamin e'],
    category: 'vitamin',
    healthConditions: ['antioxidante', 'piel', 'corazón'],
    language: 'es',
  },
  {
    id: 'vitamin-a-es',
    name: 'Vitamina A',
    aliases: ['retinol', 'vitamin a', 'beta caroteno'],
    category: 'vitamin',
    healthConditions: ['visión', 'piel', 'inmunidad'],
    language: 'es',
  },
  {
    id: 'selenium-es',
    name: 'Selenio',
    aliases: ['selenium'],
    category: 'mineral',
    healthConditions: ['antioxidante', 'tiroides', 'inmunidad'],
    language: 'es',
  },
  {
    id: 'potassium-es',
    name: 'Potasio',
    aliases: ['potassium', 'potasio'],
    category: 'mineral',
    healthConditions: ['presión arterial', 'corazón', 'músculos'],
    language: 'es',
  },
  {
    id: 'glucosamine-es',
    name: 'Glucosamina',
    aliases: ['glucosamine', 'sulfato de glucosamina'],
    category: 'other',
    healthConditions: ['articulaciones', 'cartílago', 'artritis'],
    language: 'es',
  },
  {
    id: 'chondroitin-es',
    name: 'Condroitina',
    aliases: ['chondroitin', 'sulfato de condroitina'],
    category: 'other',
    healthConditions: ['articulaciones', 'cartílago', 'artritis'],
    language: 'es',
  },
  {
    id: 'msm-es',
    name: 'MSM',
    aliases: ['metilsulfonilmetano', 'methylsulfonylmethane'],
    category: 'other',
    healthConditions: ['articulaciones', 'inflamación', 'piel'],
    language: 'es',
  },
  {
    id: 'l-carnitine-es',
    name: 'L-Carnitina',
    aliases: ['l-carnitine', 'carnitina', 'levo carnitina'],
    category: 'amino-acid',
    healthConditions: ['energía', 'pérdida de peso', 'ejercicio'],
    language: 'es',
  },
  {
    id: 'bcaa-es',
    name: 'BCAA',
    aliases: ['aminoacidos ramificados', 'leucina isoleucina valina', 'branched chain'],
    category: 'amino-acid',
    healthConditions: ['músculos', 'recuperación', 'ejercicio'],
    language: 'es',
  },
  {
    id: 'glutamine-es',
    name: 'Glutamina',
    aliases: ['l-glutamine', 'glutamina', 'l-glutamina'],
    category: 'amino-acid',
    healthConditions: ['músculos', 'intestino', 'inmunidad'],
    language: 'es',
  },
  {
    id: 'lysine-es',
    name: 'Lisina',
    aliases: ['l-lysine', 'l-lisina', 'lysine'],
    category: 'amino-acid',
    healthConditions: ['herpes', 'inmunidad', 'colágeno'],
    language: 'es',
  },
  {
    id: 'ginkgo-es',
    name: 'Ginkgo Biloba',
    aliases: ['ginkgo', 'gingko'],
    category: 'herb',
    healthConditions: ['memoria', 'circulación', 'cognición'],
    language: 'es',
  },
  {
    id: 'st-johns-wort-es',
    name: 'Hierba de San Juan',
    aliases: ['st johns wort', 'hipérico', 'hipericum'],
    category: 'herb',
    healthConditions: ['depresión', 'ánimo', 'ansiedad'],
    language: 'es',
  },
  {
    id: 'saw-palmetto-es',
    name: 'Saw Palmetto',
    aliases: ['palmito', 'serenoa repens', 'palma enana'],
    category: 'herb',
    healthConditions: ['próstata', 'cabello', 'testosterona'],
    language: 'es',
  },
  {
    id: 'milk-thistle-es',
    name: 'Cardo Mariano',
    aliases: ['milk thistle', 'silimarina', 'silybum marianum'],
    category: 'herb',
    healthConditions: ['hígado', 'desintoxicación'],
    language: 'es',
  },
  {
    id: 'spirulina-es',
    name: 'Espirulina',
    aliases: ['spirulina', 'alga espirulina'],
    category: 'other',
    healthConditions: ['antioxidante', 'proteína', 'energía'],
    language: 'es',
  },
  {
    id: 'chlorella-es',
    name: 'Chlorella',
    aliases: ['clorella', 'alga chlorella'],
    category: 'other',
    healthConditions: ['desintoxicación', 'antioxidante', 'inmunidad'],
    language: 'es',
  },
  {
    id: 'green-tea-es',
    name: 'Té Verde',
    aliases: ['green tea', 'te verde', 'egcg', 'camellia sinensis'],
    category: 'herb',
    healthConditions: ['antioxidante', 'pérdida de peso', 'metabolismo'],
    language: 'es',
  },
  {
    id: 'garcinia-es',
    name: 'Garcinia Cambogia',
    aliases: ['garcinia', 'hca', 'ácido hidroxicítrico'],
    category: 'herb',
    healthConditions: ['pérdida de peso', 'apetito'],
    language: 'es',
  },
  {
    id: 'berberine-es',
    name: 'Berberina',
    aliases: ['berberine', 'berberis'],
    category: 'herb',
    healthConditions: ['azúcar en sangre', 'colesterol', 'metabolismo'],
    language: 'es',
  },
  {
    id: 'resveratrol-es',
    name: 'Resveratrol',
    aliases: ['resveratrol'],
    category: 'other',
    healthConditions: ['antioxidante', 'corazón', 'longevidad'],
    language: 'es',
  },
  {
    id: 'alpha-lipoic-acid-es',
    name: 'Ácido Alfa Lipoico',
    aliases: ['alpha lipoic acid', 'ala', 'ácido lipoico'],
    category: 'other',
    healthConditions: ['antioxidante', 'neuropatía', 'azúcar en sangre'],
    language: 'es',
  },
  {
    id: 'l-theanine-es',
    name: 'L-Teanina',
    aliases: ['l-theanine', 'teanina', 'theanine'],
    category: 'amino-acid',
    healthConditions: ['relajación', 'ansiedad', 'enfoque', 'sueño'],
    language: 'es',
  },
  {
    id: 'tryptophan-es',
    name: 'Triptófano',
    aliases: ['l-tryptophan', 'tryptophan', '5-htp precursor'],
    category: 'amino-acid',
    healthConditions: ['sueño', 'ánimo', 'serotonina'],
    language: 'es',
  },
  {
    id: '5-htp-es',
    name: '5-HTP',
    aliases: ['5-hidroxitriptófano', '5htp', 'oxitriptan'],
    category: 'amino-acid',
    healthConditions: ['ánimo', 'sueño', 'depresión', 'apetito'],
    language: 'es',
  },
  {
    id: 'sam-e-es',
    name: 'SAM-e',
    aliases: ['s-adenosil metionina', 'same', 's-adenosylmethionine'],
    category: 'other',
    healthConditions: ['ánimo', 'articulaciones', 'hígado'],
    language: 'es',
  },
  {
    id: 'multivitamin-es',
    name: 'Multivitamínico',
    aliases: ['multivitaminico', 'multivitamin', 'complejo vitaminico'],
    category: 'other',
    healthConditions: ['salud general', 'energía', 'inmunidad', 'deficiencias'],
    language: 'es',
  },
  {
    id: 'multimineral-es',
    name: 'Multimineral',
    aliases: ['multiminerales', 'multiminerals', 'complejo mineral'],
    category: 'other',
    healthConditions: ['salud general', 'huesos', 'energía'],
    language: 'es',
  },
  {
    id: 'apple-cider-vinegar-es',
    name: 'Vinagre de Sidra de Manzana',
    aliases: ['apple cider vinegar', 'acv', 'vinagre de manzana'],
    category: 'other',
    healthConditions: ['digestión', 'azúcar en sangre', 'peso'],
    language: 'es',
  },
  {
    id: 'coconut-oil-es',
    name: 'Aceite de Coco',
    aliases: ['coconut oil', 'mct', 'mct oil'],
    category: 'fatty-acid',
    healthConditions: ['energía', 'cerebro', 'metabolismo'],
    language: 'es',
  },
  {
    id: 'garlic-es',
    name: 'Ajo',
    aliases: ['garlic', 'allium sativum', 'extracto de ajo'],
    category: 'herb',
    healthConditions: ['corazón', 'colesterol', 'presión arterial', 'inmunidad'],
    language: 'es',
  },
  {
    id: 'cranberry-es',
    name: 'Arándano Rojo',
    aliases: ['cranberry', 'arandano rojo', 'vaccinium macrocarpon'],
    category: 'herb',
    healthConditions: ['tracto urinario', 'infecciones', 'antioxidante'],
    language: 'es',
  },
  {
    id: 'dhea-es',
    name: 'DHEA',
    aliases: ['dehidroepiandrosterona', 'dehydroepiandrosterone'],
    category: 'other',
    healthConditions: ['hormonas', 'envejecimiento', 'energía'],
    language: 'es',
  },
  {
    id: 'evening-primrose-es',
    name: 'Aceite de Onagra',
    aliases: ['evening primrose oil', 'epo', 'onagra'],
    category: 'fatty-acid',
    healthConditions: ['piel', 'hormonas', 'síndrome premenstrual'],
    language: 'es',
  },
  {
    id: 'flaxseed-es',
    name: 'Linaza',
    aliases: ['flaxseed', 'aceite de linaza', 'linum usitatissimum'],
    category: 'other',
    healthConditions: ['omega-3', 'digestión', 'corazón'],
    language: 'es',
  },
  {
    id: 'aloe-vera-es',
    name: 'Aloe Vera',
    aliases: ['aloe', 'aloe barbadensis', 'sabila'],
    category: 'herb',
    healthConditions: ['digestión', 'piel', 'inflamación'],
    language: 'es',
  },
  {
    id: 'lecithin-es',
    name: 'Lecitina',
    aliases: ['lecithin', 'fosfatidilcolina', 'phosphatidylcholine'],
    category: 'other',
    healthConditions: ['cerebro', 'hígado', 'colesterol'],
    language: 'es',
  },

  // ===== MEDICINAL MUSHROOMS (English) =====
  {
    id: 'reishi-en',
    name: 'Reishi',
    aliases: ['ganoderma lucidum', 'lingzhi', 'reishi mushroom'],
    category: 'herb',
    healthConditions: ['immunity', 'stress', 'inflammation', 'sleep', 'adaptogen'],
    language: 'en',
  },
  {
    id: 'lions-mane-en',
    name: 'Lion\'s Mane',
    aliases: ['hericium erinaceus', 'lions mane mushroom', 'hericium'],
    category: 'herb',
    healthConditions: ['memory', 'cognition', 'nerves', 'focus', 'neuroprotection'],
    language: 'en',
  },
  {
    id: 'chaga-en',
    name: 'Chaga',
    aliases: ['inonotus obliquus', 'chaga mushroom'],
    category: 'herb',
    healthConditions: ['antioxidant', 'immunity', 'inflammation', 'energy'],
    language: 'en',
  },
  {
    id: 'cordyceps-en',
    name: 'Cordyceps',
    aliases: ['cordyceps sinensis', 'cordyceps mushroom'],
    category: 'herb',
    healthConditions: ['energy', 'endurance', 'performance', 'libido', 'respiration'],
    language: 'en',
  },
  {
    id: 'turkey-tail-en',
    name: 'Turkey Tail',
    aliases: ['trametes versicolor', 'coriolus versicolor'],
    category: 'herb',
    healthConditions: ['immunity', 'digestion', 'antioxidant', 'microbiome'],
    language: 'en',
  },
  {
    id: 'shiitake-en',
    name: 'Shiitake',
    aliases: ['lentinula edodes', 'shiitake mushroom'],
    category: 'herb',
    healthConditions: ['immunity', 'cholesterol', 'heart'],
    language: 'en',
  },
  {
    id: 'maitake-en',
    name: 'Maitake',
    aliases: ['grifola frondosa', 'maitake mushroom'],
    category: 'herb',
    healthConditions: ['immunity', 'blood sugar', 'weight'],
    language: 'en',
  },

  {
    id: 'multivitamin-en',
    name: 'Multivitamin',
    aliases: ['multivitamins', 'vitamin complex', 'multi'],
    category: 'other',
    healthConditions: ['general health', 'energy', 'immunity', 'deficiencies'],
    language: 'en',
  },
  {
    id: 'multimineral-en',
    name: 'Multimineral',
    aliases: ['multiminerals', 'mineral complex'],
    category: 'other',
    healthConditions: ['general health', 'bones', 'energy'],
    language: 'en',
  },
  {
    id: 'apple-cider-vinegar-en',
    name: 'Apple Cider Vinegar',
    aliases: ['acv', 'cider vinegar'],
    category: 'other',
    healthConditions: ['digestion', 'blood sugar', 'weight'],
    language: 'en',
  },
  {
    id: 'coconut-oil-en',
    name: 'Coconut Oil',
    aliases: ['mct', 'mct oil', 'medium chain triglycerides'],
    category: 'fatty-acid',
    healthConditions: ['energy', 'brain', 'metabolism'],
    language: 'en',
  },
  {
    id: 'garlic-en',
    name: 'Garlic',
    aliases: ['allium sativum', 'garlic extract'],
    category: 'herb',
    healthConditions: ['heart', 'cholesterol', 'blood pressure', 'immunity'],
    language: 'en',
  },
  {
    id: 'cranberry-en',
    name: 'Cranberry',
    aliases: ['vaccinium macrocarpon', 'cranberry extract'],
    category: 'herb',
    healthConditions: ['urinary tract', 'infections', 'antioxidant'],
    language: 'en',
  },
  {
    id: 'dhea-en',
    name: 'DHEA',
    aliases: ['dehydroepiandrosterone'],
    category: 'other',
    healthConditions: ['hormones', 'aging', 'energy'],
    language: 'en',
  },
  {
    id: 'evening-primrose-en',
    name: 'Evening Primrose Oil',
    aliases: ['epo', 'primrose oil'],
    category: 'fatty-acid',
    healthConditions: ['skin', 'hormones', 'pms'],
    language: 'en',
  },
  {
    id: 'flaxseed-en',
    name: 'Flaxseed',
    aliases: ['flax', 'flaxseed oil', 'linum usitatissimum'],
    category: 'other',
    healthConditions: ['omega-3', 'digestion', 'heart'],
    language: 'en',
  },
  {
    id: 'aloe-vera-en',
    name: 'Aloe Vera',
    aliases: ['aloe', 'aloe barbadensis'],
    category: 'herb',
    healthConditions: ['digestion', 'skin', 'inflammation'],
    language: 'en',
  },
  {
    id: 'lecithin-en',
    name: 'Lecithin',
    aliases: ['phosphatidylcholine', 'soy lecithin'],
    category: 'other',
    healthConditions: ['brain', 'liver', 'cholesterol'],
    language: 'en',
  },

  // ===== HEALTH CONDITIONS (English) =====
  {
    id: 'sleep-condition-en',
    name: 'Improve sleep',
    aliases: ['insomnia', 'better sleep', 'sleep quality'],
    category: 'condition',
    language: 'en',
  },
  {
    id: 'anxiety-condition-en',
    name: 'Reduce anxiety',
    aliases: ['stress', 'nervousness', 'calm', 'relaxation'],
    category: 'condition',
    language: 'en',
  },
  {
    id: 'energy-condition-en',
    name: 'Boost energy',
    aliases: ['fatigue', 'tiredness', 'vitality'],
    category: 'condition',
    language: 'en',
  },
  {
    id: 'muscle-condition-en',
    name: 'Build muscle',
    aliases: ['muscle mass', 'hypertrophy', 'bodybuilding'],
    category: 'condition',
    language: 'en',
  },
  {
    id: 'immunity-condition-en',
    name: 'Boost immunity',
    aliases: ['immune system', 'prevent colds', 'defenses'],
    category: 'condition',
    language: 'en',
  },
];

/**
 * Get all supplements for a specific language
 */
export function getSupplementsByLanguage(language: 'es' | 'en'): SupplementEntry[] {
  return SUPPLEMENTS_DATABASE.filter(entry => entry.language === language);
}

/**
 * Get supplement by ID
 */
export function getSupplementById(id: string): SupplementEntry | undefined {
  return SUPPLEMENTS_DATABASE.find(entry => entry.id === id);
}
